apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      {{- if eq .Release.Namespace "production" -}}
      nodePort: {{ .Values.service.productionNodePort }}
      {{- else if eq .Release.Namespace "staging" -}}
      nodePort: {{ .Values.service.stagingNodePort }}
      {{- else -}}
      nodePort: {{ .Values.service.defaultNodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-nginx