apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      {{- if eq .Release.Namespace "production" }}
      nodePort: 30090
      {{- else if eq .Release.Namespace "staging" }}
      nodePort: 30080
      {{- else }}
      nodePort: 30070
      {{- end }}
  selector:
    app: {{ .Release.Name }}-nginx