apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
data:
  index.html: |-
    <html>
    <head><title>Octopus Helm Deployment</title></head>
    <body>
    <h1>Octopus Deployment Id: {{ .Values.deploymentId }}</h1>
    <p>Namespace: {{ .Release.Namespace }}</p>
    </body>
    </html>
