apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{- if eq .Release.Namespace "production" }}
                  {{ .Values.service.productionNodePort }}
                {{- else if eq .Release.Namespace "staging" }}
                  {{ .Values.service.stagingNodePort }}
                {{- else }}
                  {{ .Values.service.defaultNodePort }}
                {{- end }}
  selector:
    app: {{ .Release.Name }}-nginx